include:
  - board: xiao_ble//zmk
    shield: totem_left raw_hid_adapter # <-- required for Raw HID support
    snippet: studio-rpc-usb-uart # <-- required for ZMK Studio support
  - board: xiao_ble//zmk
    shield: totem_right raw_hid_adapter # <-- required for Raw HID support
    snippet: studio-rpc-usb-uart # <-- required for ZMK Studio support
# there is no settingsreset (needed) for the XIAO
